### ISSUE TITLE
Failing scrapers as per 24.3.2020, 19.45

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#151]
I just ran `./meta_scrape.sh > current.txt`

Getting this output: [current.txt](https://github.com/openZH/covid_19/files/4377094/current.txt)

cc @baryluk

**Comment by baryluk** [comment]
Can you please just paste it into the issue/ I can't download the file.

Also we know they are failing. Open separate bug reports for each canton and close this issue. It is just an unecassary noise.

**Comment by zdavatz** [comment]
File is here as well: http://pillbox.oddb.org/current.txt

**Comment by zdavatz** [comment]
```
Error: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 172, in <module>
    print("{:2} {:<16} {:>7} {:>7} OK {}".format(abbr, date, cases, deaths if not deaths is None else "-", scrape_time))
TypeError: unsupported format string passed to NoneType.__format__

AG - - - FAILED
Error: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 151, in <module>
    k, v = l.split(": ")
ValueError: too many values to unpack (expected 2)

AR - - - FAILED
BE 2020-03-24T          532       6 OK 2020-03-24T19:42:07+01:00
BL 2020-03-24T14:00     306       - OK 2020-03-24T19:42:07+01:00
BS 2020-03-24T09:00     414       - OK 2020-03-24T19:42:07+01:00
GE 2020-03-23T12:00    1231       9 OK 2020-03-24T19:42:08+01:00
GL 2020-03-24T13:30       3       - OK 2020-03-24T19:42:08+01:00
GR 2020-03-24T          276       6 OK 2020-03-24T19:42:08+01:00
JU 2020-03-24T17:00      66       - OK 2020-03-24T19:42:09+01:00
LU 2020-03-24T11:00     205       - OK 2020-03-24T19:42:09+01:00
NE 2020-03-24T15:00     230       2 OK 2020-03-24T19:42:09+01:00
Error: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 151, in <module>
    k, v = l.split(": ")
ValueError: not enough values to unpack (expected 2, got 1)

NW - - - FAILED
Error: not enough values to unpack (expected 2, got 1)
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 151, in <module>
    k, v = l.split(": ")
ValueError: not enough values to unpack (expected 2, got 1)

OW - - - FAILED
Error: too many values to unpack (expected 2)
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 151, in <module>
    k, v = l.split(": ")
ValueError: too many values to unpack (expected 2)

SG - - - FAILED
SH 2020-03-24T           32       - OK 2020-03-24T19:42:10+01:00
SO 2020-03-24T00:00     104       1 OK 2020-03-24T19:42:10+01:00
Error: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 172, in <module>
    print("{:2} {:<16} {:>7} {:>7} OK {}".format(abbr, date, cases, deaths if not deaths is None else "-", scrape_time))
TypeError: unsupported format string passed to NoneType.__format__

SZ - - - FAILED
TG 2020-03-24T           87       - OK 2020-03-24T19:42:11+01:00
TI 2020-03-24T08:00    1211      53 OK 2020-03-24T19:42:11+01:00
Error: unsupported format string passed to NoneType.__format__
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 172, in <module>
    print("{:2} {:<16} {:>7} {:>7} OK {}".format(abbr, date, cases, deaths if not deaths is None else "-", scrape_time))
TypeError: unsupported format string passed to NoneType.__format__

UR - - - FAILED
Error: Unknown date/time format: Date\tHospitalisations
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 156, in <module>
    date = parse_date(v)
  File "./parse_scrape_output.py", line 128, in parse_date
    assert False, f"Unknown date/time format: {d}"
AssertionError: Unknown date/time format: Date\tHospitalisations

VD - - - FAILED
VS 2020-03-24T          544      13 OK 2020-03-24T19:42:12+01:00
ZG 2020-03-24T08:00      72       0 OK 2020-03-24T19:42:12+01:00
ZH 2020-03-24T09:30    1211       - OK 2020-03-24T19:42:12+01:00
```

**Comment by zdavatz** [comment]
@baryluk can you please also ad a timestamp for `failed`? That would be great.

**Comment by metaodi** [comment]
Closing this issue, most have already been reported in other issues, feel free to open new ones for a specific canton that has not been reported already.
