### ISSUE TITLE
Show URL in Scraper output

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#169]
@baryluk can you please also show the URL per canton your are scraping in the output of https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt or if you switch to python, show it in the output of the python-scraper. That would be really useful. 

@all please be aware that the URLs of the websites from the cantons in your daily stats [files](https://github.com/openZH/covid_19/tree/master/fallzahlen_kanton_total_csv) with the source of the information shows up on the left side of the Dashboard: http://covid19.ddrobotec.com/

So if everything is working correctly and is in sync, then the numbers here: https://www.functor.xyz/covid_19/scrapers/outputs/latest.txt and here http://covid19.ddrobotec.com/ should be in sync, including the URLs on the left of our dashboard.

**Comment by baryluk** [comment]
Can be done.

**Comment by baryluk** [comment]
It can be done very easily in a Python one. A little tricky, but doable in the bash.

I will add it in few moments.

**Comment by zdavatz** [comment]
Thank you!

**Comment by baryluk** [comment]
@zdavatz Could you verify if what is being output from scrapers, meta_scrape and parser is ok for you?

**Comment by zdavatz** [comment]
@baryluk yes, this looks good. Only thing that is missing is the timestamp if a scraper fails. Please always print the timestamp Failed or not Failed should not matter. Please do not output error messages.

```
~/.software/covid_19/scrapers> ./meta_scrape.sh 
AG 2020-03-25T15:15     319       2 OK 2020-03-26T09:28:32+01:00 https://www.ag.ch/de/themen_1/coronavirus_2/alle_ereignisse/alle_ereignisse_1.jsp
AI 2020-03-28T17:00       9       - OK 2020-03-26T09:28:33+01:00 https://www.ai.ch/themen/gesundheit-alter-und-soziales/gesundheitsfoerderung-und-praevention/uebertragbare-krankheiten/coronavirus
AR 2020-03-26T09:00      40       2 OK 2020-03-26T09:28:33+01:00 https://www.ar.ch/verwaltung/departement-gesundheit-und-soziales/amt-fuer-gesundheit/informationsseite-coronavirus/
BE 2020-03-26T          660       7 OK 2020-03-26T09:28:33+01:00 https://www.besondere-lage.sites.be.ch/besondere-lage_sites/de/index/corona/index.html
BL 2020-03-25T          341       5 OK 2020-03-26T09:28:33+01:00 https://www.statistik.bl.ch/files/sites/Grafiken/COVID19/Grafik_COVID19_BL_Linie.htm
BS 2020-03-25T10:00     466       - OK 2020-03-26T09:28:34+01:00 https://www.gd.bs.ch/, https://www.gd.bs.ch//nm/2020-tagesbulletin-coronavirus-466-bestaetigte-faelle-im-kanton-basel-stadt-gd.html
GE 2020-03-25T12:00    1604      15 OK 2020-03-26T09:28:34+01:00 
GL 2020-03-25T13:30      40       - OK 2020-03-26T09:28:34+01:00 https://www.gl.ch/verwaltung/finanzen-und-gesundheit/gesundheit/coronavirus.html/4817
GR 2020-03-25T          322       6 OK 2020-03-26T09:28:35+01:00 https://www.gr.ch/DE/institutionen/verwaltung/djsg/ga/coronavirus/info/Seiten/Start.aspx
JU 2020-03-25T18:00      78       - OK 2020-03-26T09:28:36+01:00 https://www.jura.ch/fr/Autorites/Coronavirus/Accueil/Coronavirus-Informations-officielles-a-la-population-jurassienne.html
LU 2020-03-25T11:00     228       - OK 2020-03-26T09:28:36+01:00 https://gesundheit.lu.ch/themen/Humanmedizin/Infektionskrankheiten/Coronavirus
NE 2020-03-25T14:00     256       2 OK 2020-03-26T09:28:36+01:00 https://www.ne.ch/autorites/DFS/SCSP/medecin-cantonal/maladies-vaccinations/Pages/Coronavirus.aspx
Error: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 180, in <module>
    cases = int(v)
ValueError: invalid literal for int() with base 10: 'None'

NW - - - FAILED
OW 2020-03-25T           27       - OK 2020-03-26T09:28:37+01:00 https://www.ow.ch/de/verwaltung/dienstleistungen/?dienst_id=5962
SG 2020-03-26T          280       1 OK 2020-03-26T09:28:37+01:00 https://www.sg.ch/tools/informationen-coronavirus.html
SH 2020-03-26T07:00      35       - OK 2020-03-26T09:28:37+01:00 https://sh.ch/CMS/content.jsp?contentid=3209198&language=DE&_=1584807070095
SO 2020-03-26T00:00     141       1 OK 2020-03-26T09:28:38+01:00 https://corona.so.ch/
SZ 2020-03-25T           99       - OK 2020-03-26T09:28:38+01:00 https://www.sz.ch/behoerden/information-medien/medienmitteilungen/coronavirus.html/72-416-412-1379-6948
TG 2020-03-25T           96       - OK 2020-03-26T09:28:38+01:00 https://www.tg.ch/news/fachdossier-coronavirus.html/10552
TI 2020-03-25T08:00    1354      60 OK 2020-03-26T09:28:39+01:00 https://www4.ti.ch/dss/dsp/covid19/home/
UR 2020-03-24T12:00      25       - OK 2020-03-26T09:28:39+01:00 https://www.ur.ch/themen/2920
Error: Unknown date/time format: Date\tHospitalisations
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 177, in <module>
    date = parse_date(v)
  File "./parse_scrape_output.py", line 143, in parse_date
    assert False, f"Unknown date/time format: {d}"
AssertionError: Unknown date/time format: Date\tHospitalisations

VD - - - FAILED
VS 2020-03-25T          651      14 OK 2020-03-26T09:28:40+01:00 https://www.vs.ch/de/web/coronavirus
ZG 2020-03-26T08:00      87       0 OK 2020-03-26T09:28:40+01:00 https://www.zg.ch/behoerden/gesundheitsdirektion/amt-fuer-gesundheit/corona
ZH 2020-03-25T09:30    1363       7 OK 2020-03-26T09:28:40+01:00 https://gd.zh.ch/internet/gesundheitsdirektion/de/themen/coronavirus.html
```

**Comment by baryluk** [comment]
> @baryluk yes, this looks good. Only thing that is missing is the timestamp if a scraper fails. Please always print the timestamp Failed or not Failed should not matter. Please do not output error messages.
> 
> ```
> ~/.software/covid_19/scrapers> ./meta_scrape.sh 
...
> VD - - - FAILED
...
> ```

This is unrelated to this issue.

Please open separate issue to track timestamps for failures.
