### ISSUE TITLE
UR python scraper fails

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#221]
```
UR - - - FAILED 2020-03-26T14:54:39+01:00
Error: Unknown date/time format: Date\tHospitalisations
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 177, in <module>
    date = parse_date(v)
  File "./parse_scrape_output.py", line 143, in parse_date
    assert False, f"Unknown date/time format: {d}"
AssertionError: Unknown date/time format: Date\tHospitalisations
```
cc @baryluk

**Comment by baryluk** [comment]
Unfixable at the moment. If you could contact them to stick to more sane format, that is kept consistent between days, we can then fix it.

**Comment by zdavatz** [comment]
sending an Email now to: afg@ur.ch

**Comment by MTBEnthusiast** [comment]
Wrong site, should be https://www.ur.ch/themen/2962

**Comment by baryluk** [comment]
Ah. Right. I have seen that one before. Too many things too do.

Ok. I think I just did forgot about it.

I will look into the fix.

**Comment by baryluk** [comment]
Using new URL, there is progress:

```
$ ./scrape_ur.sh 
UR
Downloading: https://www.ur.ch/themen/2962
Scraped at: 2020-03-26T16:07:54+01:00
Date and time: 26.03.2020, 12.00 Uhr
Confirmed cases: 38
Hospitalized: 4
Deaths: 0
Recovered: 2
$ ./scrape_ur.sh  | ./parse_scrape_output.py 
UR 2020-03-26T12:00      38       0 OK 2020-03-26T16:07:58+01:00 https://www.ur.ch/themen/2962
$
```

**Comment by zdavatz** [comment]
works.

**Comment by zdavatz** [comment]
Confirmation by Uri:

![latest-screenshot](https://user-images.githubusercontent.com/4953/77671417-e1560300-6f87-11ea-9ce7-83aa35f078ac.png)
