### ISSUE TITLE
Python Scrapper for VD fails

### ISSUE THREAD

**Issue by zdavatz** [openZH/covid_19#231]
```
Error: Unknown date/time format: Date\tHospitalisations
Traceback (most recent call last):
  File "./parse_scrape_output.py", line 177, in <module>
    date = parse_date(v)
  File "./parse_scrape_output.py", line 143, in parse_date
    assert False, f"Unknown date/time format: {d}"
AssertionError: Unknown date/time format: Date\tHospitalisations

VD - - - FAILED 2020-03-26T16:18:28+01:00
```
cc @baryluk 

besides from that, they now all work! Congratulations!

**Comment by zdavatz** [comment]
works! https://github.com/openZH/covid_19/pull/230

**Comment by baryluk** [comment]
There are no Python scraper for VD.

As you already know, this is due to bash.

Yes, #230 is a "fix".
