### ISSUE TITLE
VS: check why scraper does not fail

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#545]
```
Populating database from CSV COVID19_Fallzahlen_Kanton_VS_total.csv...
Run the scraper...
Traceback (most recent call last):
  File "/home/runner/work/covid_19/covid_19/scrapers/scrape_vs.py", line 40, in <module>
    d = sc.pdfdownload(full_url, raw=True)
  File "/home/runner/work/covid_19/covid_19/scrapers/scrape_common.py", line 57, in pdfdownload
    with subprocess.Popen(pdf_command, stdin=pdf.stdout, stdout=subprocess.PIPE) as text:
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pdftotext': 'pdftotext'
WARNING: Expected Hospitalized to be present for VS
WARNING: Expected ICU to be present for VS
WARNING: Expected Vent to be present for VS
WARNING: Expected Released to be present for VS
WARNING: Expected time of a day to be present for VS. Found none.
{'date': '2020-04-17', 'time': '', 'area': 'VS', 'tested': '', 'confirmed': 1730, 'new_hospitalized': '', 'hospitalized': '', 'icu': '', 'vent': '', 'released': '', 'deceased': 96, 'source': 'https://www.vs.ch/de/web/coronavirus'}
```

**Comment by metaodi** [comment]
Fixed with https://github.com/openZH/covid_19/commit/c5d74a5caa150ae42e1e32d3a026416e486850e1
