### ISSUE TITLE
NW scraper fails with "unknown date/time format"

### ISSUE THREAD

**Issue by metaodi** [openZH/covid_19#556]
[Failed run](https://github.com/openZH/covid_19/runs/597985282):

```
Run the scraper...
NW Error: Unknown date/time format: 18. April 2020,16.00 Uhr
Traceback (most recent call last):
  File "/home/runner/work/covid_19/covid_19/scrapers/parse_scrape_output.py", line 278, in <module>
    new_date = parse_date(v)
  File "/home/runner/work/covid_19/covid_19/scrapers/parse_scrape_output.py", line 173, in parse_date
    assert False, f"Unknown date/time format: {d}"
AssertionError: Unknown date/time format: 18. April 2020,16.00 Uhr
```

**Comment by metaodi** [comment]
Note that NW now provides an excel sheet (see #538), so maybe we can switch to that instead of fixing for the old source.
